[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]


[project]
name = "solardem"
version = "0.0.1"
dependencies = [
    "astropy",
    "numpy",
    "scipy"
]

[mypy-astropy]
ignore_missing_imports = "True"
